### ISSUE TITLE
Plan for winter/spring!

### ISSUE THREAD

**Issue by Emzichan** [piratpartiet/skutan#3]

**Comment by Emzichan** [comment]
**# Vinter**
- [x] Dritbox läcker (Emelie & Gonte)
- [x] GSM-larm (Emelie & Gonte)
- [x] Nåta resten av däcket (Emelie & Gonte)
- [x] Bjud in person från Isegran att komma o titta på kölsvinet / kölbultarna o ge offert för att fixa om behövs.
Omnåtning av skrovet på relevanta ställen kan behöva ingå / göras även om kölbultarna är ok
- [ ] **Byta kablar för lantärnor (Gonte & Emelie)**
- [x] **Göra klart livbojshållare (Emelie & Gonte)**
- [x] Montera upp lantärnbehållare (Emelie & Gonte)
- [ ] Hyllsystem i skåpet (Emelie & Gonte)
- [ ] Låda & durk (Emelie & Gonte)
- [ ] Handtag på durken (Emelie)
- [ ] Vålda skorstenstopp & kolla hur det ser ut innuti :) Montera tillbaka "löst" så det inte regnar in
- [ ] **Cigguttag i kojerna**
- [x] Sanera kölsvinet (aka vafan är det som luktar?!)
- [ ] **Städa~**
- [ ] **Mäta saker (vanter, det kungliga skåpet, sittbrunnen)**
- [x] **Olja. Mer. :)**
- [x] **Flytta fram båtdjäveln**
- [x] **Prata med Atle om kabel**

**# Vår**
- [ ] Aktervägg i styrhytt (Emelie & Gonte) (tidig vår)
- [x] Balk på styrbord sida (Egil) 
- [ ] Nåta om däck under relingens knä längst fram (Egil kapar, Emelie & Gonte nåtar)
- [ ] Roder (Egil)
- [ ] Kaminmontage (Egil)
- [ ] Slangar till sittbrunnen

**# Materialinköp inför våren**
- [ ] Vermiculit-platta, distanser, skorstensrör för kaminmontage
- [ ] Ekplank för vägg till styrhytt (mät yta, räkna längder, vi kan inte skarva - gör en design!)
- [ ] Balk till styrbord sida i furu (mät längd och bredd, ta med både längsgående och tvärgående balk)
- [ ] Hitta & Beställa LED-lampor till lantärnorna E12 / E10 (Gonte)?

- [ ] Kolla / köp ny multitool

- Planera för nästa års segling
- Plannera vårens byggveckor (synca inköp av virke)
- Plannera presseningshämtande (synca med Benny & Ylva!)

**Comment by redhog** [comment]
![balk](https://user-images.githubusercontent.com/104229/37227902-0aa511f2-23df-11e8-8763-3b28eb203bc3.png)

**Comment by redhog** [comment]
https://www.nackabyggnadsvard.se/thumb/6567/550x0/Ny-dorr.JPG

**Comment by redhog** [comment]
![vagg](https://user-images.githubusercontent.com/104229/37228143-dd5ec944-23df-11e8-9de9-06710d35dd68.png)

**Comment by redhog** [comment]
![bord](https://user-images.githubusercontent.com/104229/37228807-295433b4-23e2-11e8-9365-f8887ce75093.png)

**Comment by redhog** [comment]
[Bryggekart.pdf](https://github.com/piratpartiet/skutan/files/1798418/Bryggekart.pdf)
